# Generated by Django 3.1.2 on 2020-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('ER', 'earrings'), ('RI', 'ring'), ('NL', 'necklace')], max_length=2),
        ),
    ]
